// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Force use of environment variables from .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://zxbydjiptihzsxucvynp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_OfJIxmZ_jiVGS4boYvt2Gg_BMRxUkKc';

console.log("Supabase config:", {
  URL: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY && SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key',
  keyLength: SUPABASE_PUBLISHABLE_KEY?.length,
  isProduction: import.meta.env.PROD,
  envVars: {
    url: !!import.meta.env.VITE_SUPABASE_URL,
    key: !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    anonKey: !!import.meta.env.VITE_SUPABASE_ANON_KEY
  }
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});